### ISSUE TITLE
Debugging errors properly

### ISSUE THREAD

**Issue by snwfdhmp** [gswly/dctoolkit#1]
### You should not panic(err)

https://github.com/gswly/dctoolkit/blob/16d00511a196874de8c6d01751f933c9c15ffacd/test/17download_dir.go#L14-L25

Hey dude,

Just a friendly advice. You should not panic(err). You’d rather use [a package like this](https://github.com/snwfdhmp/errlog) for debugging your errors. Debug your code with :

1. Clear stack trace
2. Failing func call highlighting

<img width="999" alt="example" src="https://user-images.githubusercontent.com/23099246/53098953-11310c80-3525-11e9-8f6f-302791743cdf.png">

It’s way more easier then to debug.

Real better than panic-ing (in most case). You can still force exit if you need it.

I would be happy to get your feedbacks.

**Comment by gswly** [comment]
Hello, thank you for the message. The reason behing panic() is that it doesn't require any external dependency, it's a primitive. It is seldom used in the library, it is used in tests (that are completely non-standard but are effective), and is used in example, where users are expected to replace it with their error handling method.

So: i'm willing to replace panic() in the main library but with a portable solution, i'd rather not add an additional dependency, since i've managed to keep this project almost dependency-free.
